#!/bin/sh

templ=howto/template.tpl
#LORE=`which lore` # "/usr/bin/lore"
LORE="/home2/fantixor/system/bin/lore"
NIGHTLY="/home2/fantixor/twisted-doc-zh/nightly"
DEST="$NIGHTLY/online"
BUILD=`date +%Y%m%d`
date +%Y-%m-%d > $NIGHTLY/latest
TAR="$NIGHTLY/twisted-doc-zh_nightly_$BUILD.tar.gz"
CURRENT="/home2/fantixor/twisted-doc-zh/trunk"
VERSION="8.10"

rm $DEST -rf
cp $CURRENT $DEST -R
cd $DEST
for doc in . man examples howto howto/tutorial howto/policy specifications upgrades upgrades/2.0 ; do
#for doc in ./ ; do
	if [ -e "$doc" ]; then
		echo "Proccessing $doc"
		link_rel=$(echo $doc | sed -e 's/\(^\|\/\)[^.\/]\+/\1../g')/howto/

		$LORE -p --config baseurl=http://twistedmatrix.com/documents/current/api/%s.html --config template=$templ --config ext=.html --config version=$VERSION -l $link_rel $doc/*.xhtml
	else
		echo "Skipping non-existent $doc"
	fi
done

echo "\nCleaning up..."
#svn ls -R | xargs rm
find | grep xhtml | xargs rm
find | grep "\.svn" | xargs rm -rf

echo "\nCopying necessary files..."
cp $CURRENT/howto/stylesheet.css howto/
echo "Fixing problems left by lore..."
find . -name "*.html" | xargs perl -pi -e 's/\<h2\>Footnotes\<\/h2\>/\<h2\>脚注\<\/h2\>/g'
find . -name "*.html" | xargs perl -pi -e 's/\<\?xml\ version\=\"1\.0\"\?\>/\<\?xml\ version\=\"1\.0\"\ encoding\=\"UTF\-8\"\?\>/g'

echo "\nArchiving..."
cd $NIGHTLY
mv online twisted-doc-zh_nightly_$BUILD
tar czvf $TAR twisted-doc-zh_nightly_$BUILD
mv twisted-doc-zh_nightly_$BUILD online
